name: Compile LaTeX Resume and Deploy to gh-pages Directory

on:
  push:
    branches:
      - main  # or the branch you want to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive

      - name: Compile LaTeX document
        run: |
          pdflatex resume.tex

      - name: Create gh-pages Directory
        run: mkdir -p gh-pages

      - name: Deploy to GitHub Pages
        run: |
          cp resume.pdf gh-pages/
        - uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./gh-pages
